### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by dprastha** [Avlach30/movie-api-dot-onboarding#2]
## Description
- Usahakan di codingan tetap menggunakan `camelCase`, bisa pakai `Expose()` dari `class-transformer`, cek di entity dan DTO yang lain juga
![image](https://user-images.githubusercontent.com/57651747/184300109-d6a7e934-d57c-4ecc-855d-52e1edc0f24e.png)

**Comment by dprastha** [comment]
ini belum dibenerin pakai `@Expose()`, tolong cek di file lain juga yaa mas @Avlach30 
![image](https://user-images.githubusercontent.com/57651747/184627270-ddde60d5-a24d-4393-9b65-b1e0a125b688.png)

**Comment by Avlach30** [comment]
Oh iya baik mas
